{% set name = "colour-science" %}
{% set version = "0.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/colour_science-{{ version }}.tar.gz
  sha256: be98c2c9b2a5caf0c443431f402599ca9e1cc7d944bb804156803bcc97af4cf0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - hatch
  run:
    - python >=3.10,<3.14
    - imageio >=2,<3
    - matplotlib-base >=3.7
    - numpy >=1.24,<3
    - scipy >=1.10,<2
    - trimesh >=4,<5
    - typing_extensions >=4,<5

test:
  imports:
    - colour
    - colour.colorimetry
    - colour.io
    - colour.plotting
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.colour-science.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Colour Science for Python'
  doc_url: https://colour.readthedocs.io/
  dev_url: https://github.com/colour-science/colour

extra:
  recipe-maintainers:
    - KelSolaar
    - MichaelMauderer
