{% set name = "colour-science" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/colour-science-{{ version }}.tar.gz
  sha256: 709f9d1228c46b34e961d2ae4b82c8a97b261ba8534f3301d54aa3fec75b54da

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - poetry
  run:
    - python >=3.8,<3.11
    - imageio >=2,<3
    - numpy >=1.19,<2
    - scipy >=1.5,<2
    - typing_extensions >=4,<5
    - matplotlib-base >=3.2,!=3.5.0,!=3.5.1

test:
  imports:
    - colour
    - colour.colorimetry
    - colour.io
    - colour.plotting
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.colour-science.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Colour Science for Python
  doc_url: https://colour.readthedocs.io/
  dev_url: https://github.com/colour-science/colour

extra:
  recipe-maintainers:
    - KelSolaar
    - MichaelMauderer
